### PR TITLE
Better error in verify_is_valid_tls_server_cert

### PR DESCRIPTION
**Pull request by stepancheg**
Before this commit `UnknownIssuer` was emitted on any error of
verifying the anchor to the certificate.

Now the most important error is returned. In particular,
`UnsupportedSignatureAlgorithm` is returned on, well, unsupported
signature algorithm.

I agree to license my contributions to each file under the terms
given at the top of each file I changed.

### CODE REVIEW

**Comment by briansmith** [comment]
It is intentional that webpki does not do this. I discussed why in an issue that was closed recently. There are a lot of improvements that we need to make before we can consider adding this much complexity.

**Comment by stepancheg** [comment]
You probably reference this issue https://github.com/briansmith/webpki/issues/183

And the reason must be this:

> As far as this webpki crate is concerned, simplicity and portability (to small embedded systems) is valued over the quality of the contents of errors returned. My expectation is that webpki would be used in the core trusted computing base of the systems that use it, but that detailed certificate diagnostics would live outside the TCB, in a highly restricted sandbox.

This PR generally does not violate it: it adds only a little runtime overhead, like 50 bytes of code size, and barely noticeable performance overhead, and no data size overhead.

As I mentioned in another issue, setting up rustls is hard. When openssl works fine, it is not a guarantee, that rustls will work with the same certificates for various reasons (including for example differences in how the client/server is configured). I'm stuck trying to make rustls rust, so that's why I started submitting these PRs.

> Does not add extra checks to the parser in the non-error case
> is net 1 or less lines of code (often it will be net 0 lines of code)

If it is the binary size, it can be dealt with. One possible approach is to add an optional logging dependency, disabled for no-std. (Although, ideally it should both logging and correct errors.)

> There are a lot of improvements that we need to make before we can consider adding this much complexity.

When these planned things are done properly, current ad-hoc diagnostic can be reverted.

Well, obviously I'm not going to try too hard to convince. If the library is considered working as designed, I'll just use `println!()` in my local copy without submitting results of my findings as PRs.

**Comment by briansmith** [comment]
The issue I was thinking of was actually a PR that does more or less the same thing as this PR: #140. I'm still not convinced it is worth doing, but also I think this has been requested like 3 times so we can revisit it when the higher priority stuff is complete.

**Comment by stepancheg** [comment]
OK, the problem was in that webpki did not support `sha1WithRSAEncryption`.

And that error `UnknownIssuer` and previous `BadDER` errors are not just unhelpful, they are misleading. I would find the issue faster if the error was just something like `Error::Unknown`, so I would go straight to inserting `println!()` in the library, which I did in the end.

> I'm still not convinced it is worth doing

Sorry to hear that.

**Comment by briansmith** [comment]
I filed an issue about doing something similar to this: #206.

**Pull request closed without merging**
