### PR TITLE
Added support for trusting self-signed certificates

### PR DESCRIPTION
**Pull request by jbg**
Added a flag `is_end_entity` to `TrustAnchor` for self-signed certs, and deferred the `CAUsedAsEndEntity` error returned by `check_issuer_independent_properties()` to be checked again once the matching trust anchor is found, returning the error if the trust anchor is not flagged as an end entity.

Added tests verifying the acceptance of a self-signed certificate when a `TrustAnchor` with `is_end_entity: true` is present for the certificate, and verifying the rejection of the same certificate when it is not.

### CODE REVIEW

**Comment by eupn** [comment]
@briansmith any chance this getting merged?

**Comment by jbg** [comment]
@briansmith please let me know if I can do anything to help get this across the line.

**Comment by jbg** [comment]
@briansmith in March you said "I would be happy to review a PR that adds such a mechanism with appropriate tests." This is that PR, which I sent more than half a year ago.

Would you still be happy to review it?

It was only an hour or two of work, which I needed to do anyway in order to use it in my own project, but I took the additional time to add tests and open the PR. Even if you've changed your mind and are no longer interested in adding this feature to webpki, it would be great if you could say that rather than just ignore the PR. If webpki will never gain this feature then I'll need to look at replacing it in my projects, rather than perpetually using my fork.

**Comment by briansmith** [comment]
Thank you. Please see https://github.com/briansmith/webpki/issues/114#issuecomment-759842242 to understand why I'm closing this.

**Pull request closed without merging**
