### PR TITLE
Add a method to collect the DNS names from a certificate

### LINKED ISSUE #64: Add method to get all the names from a certificate
Hi,
To integrate [rustls in sozu](https://github.com/sozu-proxy/sozu/issues/145), I'd need a way to get the common name and subject alternative names from a certificate, and apparently I should implement it on `EndEntityCert`. I opened a [related issue in rustls](https://github.com/ctz/rustls/issues/140).
If you're ok with this feature, I could work on a PR tomorrow.

### PR DESCRIPTION
**Pull request by seanmonstar**
This continues on the work from #65, and adds what seems to have been missing per the review:

- Added a test that a certificate that contains wildcards in its Subject Alternative Name list has the wildcard skipped when returning the list.
- I also changed the behavior for the test `invalid_subject_alternative_names`. Instead of returning a `BadDER` error because *one* name wasn't a valid `DNSName`, those names are just skipped instead.

Closes #64

### CODE REVIEW

**Comment by seanmonstar** [comment]
Looks like CI failures are spurious `apt-get` errors?

**Comment by Geal** [comment]
Why skip wildcard names? This is the kind of information I'd like to gather from a certificate. Or is there another way to get it?

**Comment by briansmith** [comment]
> Why skip wildcard names? This is the kind of information I'd like to gather from a certificate. Or is there another way to get it?

I support adding support for wildcards as long as non-wildcard and wildcard names are explicitly distinguished in the type system, e.g. adding a `WildcardDnsName` type and then having this kind of functionality return an `enum GeneralDnsName { DnsName(DnsName), WildCard(WildCardDnsName) }`.

**Comment by briansmith** [comment]
Closing this in favor of PR #103. PLMK if this was the wrong thing to do.

Note: I renamed the "master" branch to "main". Sorry for the inconvenience. This PR has had its base branch updated to "main" but you'll need to deal with the change in your local repo yourself.

**Pull request closed without merging**
