### PR TITLE
Add support for verifying client certificates	

### PR DESCRIPTION
**Pull request by alex**
This is a continuation of #43

### CODE REVIEW

**Comment by udpip7** [comment]
Can we get this change into master?  I think the only thing unaddressed from your comments in #43 is the client-auth callbacks.  I don't think you really need that at the webpki level though.  I wouldn't have issued the certificate if I didn't verify the identity and I can get the identity from the certificate myself after rustls/webpki verifies the chain.  As it is now rustls own client verification fix is blocked and I can't use it at all.

**Comment by briansmith** [comment]
OK. Thanks for submitting this PR. This PR looks like a reasonable foundation, at least, for adding client certificate support. I'm going to merge the `Time` changes first, and also experiment with using this, experiment with adding some client name validation support that's lacking here, and then circle back around to reviewing this.

**Comment by briansmith** [comment]
@ctz Are you open to changing the webpki-roots, Rustls, etc. crates to use the `TLSServerTrustAnchors` type for the trust anchor list? Any thoughts on this?

**Comment by ctz** [comment]
Yes, that sounds like a good idea too.

**Comment by briansmith** [comment]
This formed part of the client cert implementation that's in master now. Thanks!

**Pull request closed without merging**
